changes

diff --git a/0x05-processes_and_signals/101-manage_my_process b/0x05-processes_and_signals/101-manage_my_process
--- a/0x05-processes_and_signals/101-manage_my_process
+++ b/0x05-processes_and_signals/101-manage_my_process
@@ -1,31 +1,29 @@
 #!/usr/bin/env bash
-# This script manages 'manage_my_process'
-#!/usr/bin/env bash
 # Manages 'manage_my_process'
 
-if [ $# -gt 0 ]
-then
-    if [ "$1" == "start" ]
-    then
+if [ $# -gt 0 ]; then
+    if [ "$1" == "start" ]; then
         ./manage_my_process &
-        touch /var/run/my_process.pid
-
         echo "$!" > /var/run/my_process.pid
         echo "manage_my_process started"
-    elif [ "$1" == "stop" ]
-    then
-
+    elif [ "$1" == "stop" ]; then
         echo "manage_my_process stopped"
-        kill "$(cat /var/run/my_process.pid)"
-        rm -f /var/run/my_process.pid
-    elif [ "$1" == "restart" ]
-    then
-
-        kill "$(cat /var/run/my_process.pid)"
-        rm -f /var/run/my_process.pid
+        if [ -f /var/run/my_process.pid ]; then
+            kill "$(cat /var/run/my_process.pid)"
+            rm -f /var/run/my_process.pid
+        else
+            echo "Error: PID file not found."
+            exit 1
+        fi
+    elif [ "$1" == "restart" ]; then
+        if [ -f /var/run/my_process.pid ]; then
+            kill "$(cat /var/run/my_process.pid)"
+            rm -f /var/run/my_process.pid
+        else
+            echo "Error: PID file not found."
+            exit 1
+        fi
         ./manage_my_process &
-
-        touch /var/run/my_process.pid
         echo "$!" > /var/run/my_process.pid
         echo "manage_my_process restarted"
     else
